name: Lint & Test Types
on:
    push:
    pull_request:
        types: [reopened]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: Lint & Test Types
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "lts/*"

            - run: npm install
            - run: npm run lint:ci
            - name: Detect changes
              id: changes
              run: echo "count=$(git status --porcelain=v1 2>/dev/null | wc -l)" >> $GITHUB_OUTPUT
            - name: Fail if there are uncommitted changes
              if: steps.changes.outputs.count > 0
              run: exit 1
